package maps

var restaurantTypes = map[string]string{
	"acai_shop":                 "Acai Shop",
	"afghani_restaurant":        "Afghani",
	"african_restaurant":        "African",
	"american_restaurant":       "American",
	"asian_restaurant":          "Asian",
	"bagel_shop":                "Bagel Shop",
	"bakery":                    "Bakery",
	"bar":                       "Bar",
	"bar_and_grill":             "Bar and Grill",
	"barbecue_restaurant":       "Barbecue",
	"brazilian_restaurant":      "Brazilian",
	"breakfast_restaurant":      "Breakfast",
	"brunch_restaurant":         "Brunch",
	"buffet_restaurant":         "Buffet",
	"cafe":                      "Cafe",
	"cafeteria":                 "Cafeteria",
	"candy_store":               "Candy Store",
	"cat_cafe":                  "Cat Cafe",
	"chinese_restaurant":        "Chinese",
	"chocolate_factory":         "Chocolate Factory",
	"chocolate_shop":            "Chocolate Shop",
	"coffee_shop":               "Coffee Shop",
	"confectionery":             "Confectionery",
	"deli":                      "Deli",
	"dessert_restaurant":        "Dessert",
	"dessert_shop":              "Dessert Shop",
	"diner":                     "Diner",
	"dog_cafe":                  "Dog Cafe",
	"donut_shop":                "Donut Shop",
	"fast_food_restaurant":      "Fast Food",
	"fine_dining_restaurant":    "Fine Dining",
	"food_court":                "Food Court",
	"french_restaurant":         "French",
	"greek_restaurant":          "Greek",
	"hamburger_restaurant":      "Hamburger",
	"ice_cream_shop":            "Ice Cream Shop",
	"indian_restaurant":         "Indian",
	"indonesian_restaurant":     "Indonesian",
	"italian_restaurant":        "Italian",
	"japanese_restaurant":       "Japanese",
	"juice_shop":                "Juice Shop",
	"korean_restaurant":         "Korean",
	"lebanese_restaurant":       "Lebanese",
	"meal_delivery":             "Meal Delivery",
	"meal_takeaway":             "Meal Takeaway",
	"mediterranean_restaurant":  "Mediterranean",
	"mexican_restaurant":        "Mexican",
	"middle_eastern_restaurant": "Middle Eastern",
	"pizza_restaurant":          "Pizza",
	"pub":                       "Pub",
	"ramen_restaurant":          "Ramen",
	"restaurant":                "Restaurant",
	"sandwich_shop":             "Sandwich Shop",
	"seafood_restaurant":        "Seafood",
	"spanish_restaurant":        "Spanish",
	"steak_house":               "Steak House",
	"sushi_restaurant":          "Sushi",
	"tea_house":                 "Tea House",
	"thai_restaurant":           "Thai",
	"turkish_restaurant":        "Turkish",
	"vegan_restaurant":          "Vegan",
	"vegetarian_restaurant":     "Vegetarian",
	"vietnamese_restaurant":     "Vietnamese",
	"wine_bar":                  "Wine Bar",
}
